### ISSUE TITLE
hasSubsequence implementation 

### ISSUE THREAD

**Issue by goral09** [fpinscala/fpinscala#279]
Hi, I just read your implementation of `hasSubsequence` and compared it with mine:

```
def hasSubsequence[A](l: List[A], sub: List[A]): Boolean = (l, sub) match {
    case (_, Nil)   => true
    case (Nil, _)   => false
    case (Cons(h1,t1), Cons(h2,t2)) => if(h1 == h2) hasSubsequence(t1, t2) else hasSubsequence(t1, Cons(h2,t2))
}
```

can you tell me what is wrong with mine?

**Comment by haol615** [comment]
Hey I just found this thread - It seems this one returns wrong answer for hasSubsequence(List(1,2,3,4), List(1,3))? I think 1::3::Nil is not a subsequence for 1::2::3::4::Nil, but this answer gives true. Any thoughts?

**Comment by runarorama** [comment]
Yeah, @haol615 is right, this answer is incorrect. Looks like this was never added to the answers file though, and there's no open PR for it either.

**Comment by pchiusano** [comment]
Shall we just close this then?

**Comment by runarorama** [comment]
It is closed
