### ISSUE TITLE
Exercise 3.24: hasSubsequence - case of Nil subsequence

### ISSUE THREAD

**Issue by sergius** [fpinscala/fpinscala#359]
In the exercise's description is given the following example:
*"... For instance, `List(1,2,3,4)` would have `List(1,2)` , `List(2,3)` , and `List(4)` as subsequences, among others..."*
No mention of empty list as valid subseguence.

This is the proposed solution:
```
  def startsWith[A](l: List[A], prefix: List[A]): Boolean = (l,prefix) match {
    case (_,Nil) => true
    case (Cons(h,t),Cons(h2,t2)) if h == h2 => startsWith(t, t2)
    case _ => false
  }
  @annotation.tailrec
  def hasSubsequence[A](l: List[A], sub: List[A]): Boolean = l match {
    case Nil => false
    case Cons(h,t) if startsWith(l, sub) => true
    case Cons(h,t) => hasSubsequence(t, sub)  
  }
```
The solution implies that when the list of subsequence (`sub`) is `Nil` the result is `true`, meaning that `List()` is a subsequence of any other `List`. This reasoning might be accepted, but if so then I believe that it *should be explicitely mentioned in the problem description*. 

Otherwise, the solution should be changed to something like this:
```
  def hasSubsequence[A](l: List[A], sub: List[A]): Boolean = (l, sub) match {
    case (Nil, _) => false
    case (_, Nil) => false
    case (_, _) if startsWith(l, sub) => true
    case (Cons(_,t), _) => hasSubsequence(t, sub)
  }
```

**Comment by ailveen** [comment]
I agree with the last solution that an empty List is NOT a subsequence of a non-empty List. 

If we allow this i.e. in production code (exaggerating), it can be disastrous - for instance - imagine a use case where hasSubsequence checks if the user has completed pre-requisites in order and the user has not even completed 1 pre-requisite (empty list).

I will submit a pull request for this.

**Comment by runarorama** [comment]
I'd say we probably want to allow that the empty string is a substring of any string.

E.g.:

```
scala> "foo".contains("")
res3: Boolean = true
```

We should probably change the problem description to make this more clear. However, this is *your* library that you're building, and *you* make the rules.
