### ISSUE TITLE
Excercise 5.13, takeViaUnfold method, redundant case "if n == 1"

### ISSUE THREAD

**Issue by gothug** [fpinscala/fpinscala#364]
Can't we just implement it like this:

  def takeViaUnfold(n: Int): Stream[A] =
    unfold((this, n)) {
      case (Cons(h, t), x) if x > 0 => Some(h(), (t(), x - 1))
      case _                        => None
    }

?

Why do we need this separate case: 

case (Cons(h,t), n) if n == 1 => Some((h(), (empty, n-1)))

?

Please correct me if I'm wrong and missing something, thanks.

**Comment by pegomes** [comment]
@gothug This appears to be a valid simplification. I came up with the same solution and was googling about it and found this issue that you created. Would you like me to submit a pull request for it? I would of course give you credit for the solution. Cheers - pegomes :)

**Comment by pegomes** [comment]
@gothug I went ahead and submitted a pull request. I hope you don't mind. Cheers - pegomes :)

**Comment by mpilquist** [comment]
The extra case ensures that the tail is not evaluated and then immediately thrown away. The same optimization is used in the answer to 5.2 (take implemented via recursion).
