### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by ppiotrow** [fpinscala/fpinscala#411]
After the latest commit 617b92727a75a1a85508dbbe36ea09c595d92718 I couldn't compile source.

[error] (...)/src/main/scala/fpinscala/iomonad/Monad.scala:27: forward reference extends over definition of value t
[error]     val t: F[B] = a flatMap (_ => t)
[error]                                   ^
[error] one error found
[error] (...)/src/main/scala/fpinscala/iomonad/Monad.scala:27: forward reference extends over definition of value t
[error]     val t: F[B] = a flatMap (_ => t)
[error]                                   ^
[error] one error found

**Comment by runarorama** [comment]
Apparently that val has to be lazy.
