### ISSUE TITLE
Gitter channel?

### ISSUE THREAD

**Issue by dwijnand** [fpinscala/fpinscala#413]
Sometimes I have questions related to topics from the book, where I'd prefer to throw it in a chat instead of creating an email thread. What do people think about creating a Gitter channel? It would be https://gitter.im/fpinscala/fpinscala

**Comment by toxicafunk** [comment]
Sounds like a great idea to me!!!!

+1

**Comment by S11001001** [comment]
This has been mentioned in README since 0496aa8.

NB: the [IRC channel #fp-in-scala on Freenode](http://webchat.freenode.net?channels=%23fp-in-scala) is also available, and has been around for a while.

**Comment by dwijnand** [comment]
Thanks.
