### ISSUE TITLE
Answer 7.3 uses System.currentTimeMillis instead of System.nanoTime

### ISSUE THREAD

**Issue by tilois** [fpinscala/fpinscala#420]
Just a small improvement, the current implementation of the [answer for 7.3](https://github.com/fpinscala/fpinscala/blob/master/answerkey/parallelism/03.answer.scala) uses `System.currentTimeMillis` for measuring the duration it took to compute `at`.

That is bad practise and should be avoided. The method to use instead is `System.nanoTime` instead.
The reasoning behind this is that `nanoTime`:
  * is specificially made for measuring durations
  * is not affected by leap-seconds, leap-hours, ...
  * is not affected if the user sets the system clock in the meanwhile
  * could theoretically be more precise

That has nothing to do with the actual content which is covered by the book though.

**Comment by runarorama** [comment]
Sounds good. Looking forward to the pull request! :smile:

**Comment by tilois** [comment]
I could have seen this one coming. :laughing:
