### ISSUE TITLE
gettingstarted/01.answer.scala - does not cover edge cases for n = 1 and n = 2

### ISSUE THREAD

**Issue by aferdous** [fpinscala/fpinscala#429]
**current implementation**
  def fib(n: Int): Int = {
    @annotation.tailrec
    def loop(n: Int, prev: Int, cur: Int): Int =
      if (n == 0) prev
      else loop(n - 1, cur, prev + cur)
    loop(n, 0, 1)
  } 
** and correct implementation**
  def fib(n: Int): Int = {
    @annotation.tailrec
    def loop(n: Int, prev: Int, cur: Int): Int =
      if (n == 1) prev
      else if (n == 2) cur
      else loop(n - 1, cur, prev + cur)
    loop(n, 0, 1)
  }

**Comment by runarorama** [comment]
I'm not sure what you mean. The first two numbers in the sequence should be 1.

**Comment by aferdous** [comment]
fibonacci sequence (as described in the book and couple of other online resources) is 0 , 1, 2, 3, ,5 ,8 and so on. The exercise asks to calculate the nth Fibonacci number where n > 0 (there is not 0th element in Fib series). 

fib(1) = 0 // the first one in the list
fib(2) = 1 // the second one in the list.
fib(3) = 1 // the 3rd one in the list
fib(4) = 2 // the 4th one in the list

This is my understanding of the problem.

**Comment by runarorama** [comment]
Whether the Fibonacci sequence starts [0, 1, 1. ...] or [1, 1, ...] isn't all that important to the exercise, but you are right that we do say in the book that we consider it to start with 0.

I'd prefer this version:

```
def fib(n: Int): Int = {
  @annotation.tailrec
    def loop(n: Int, prev: Int, cur: Int): Int =
      if (n <= 0) prev
      else loop(n - 1, cur, prev + cur)
      loop(n, 0, 1)
}
```

We strongly prefer [zero-based numbering](https://en.wikipedia.org/wiki/Zero-based_numbering), but your preference is of course up to you.
