### ISSUE TITLE
datastructures 05.answer.scala（EXERCISE3.5）

### ISSUE THREAD

**Issue by yshutaro** [fpinscala/fpinscala#451]
```
def dropWhile[A](l: List[A], f: A => Boolean): List[A] = 
  l match {
    case Cons(h,t) if f(h) => dropWhile(t, f) 
    case _ => l
  }
```
I think the correct answer as following.
if(h) -> !if(h)
```
    case Cons(h,t) !if f(h) => dropWhile(t, f) 
```

**Comment by runarorama** [comment]
No, the given answer is correct. If the predicate `f` matches the head of the list, then we continue recursing over the tail of the list, "dropping" the head.
