### ISSUE TITLE
Chapter 5: answers: where do `Cons` and  `Empty` come from

### ISSUE THREAD

**Issue by capitanbatata** [fpinscala/fpinscala#457]
Maybe I missed it, but I cannot trace in the book or in the exercises where these two constructors are defined. I assume they are subtypes of Stream. But some clarification may be in order.

**Comment by pascalh** [comment]
Both constructors are introduced in listing 3.1.

**Comment by capitanbatata** [comment]
Oh, thanks. I guess this is in the latest version of the book (I have the MEAP v10). I guess I should get a print out.
