### ISSUE TITLE
Issue with statement in exercise 6.1

### ISSUE THREAD

**Issue by higuaro** [fpinscala/fpinscala#484]
In chapter 6, page 81 (102 for the electronic version), the following algorithm to calculate pseudo-random numbers is given: 

``` scala
case class SimpleRNG(seed: Long) extends RNG {
   def nextInt: (Int, RNG) = {
      val newSeed = (seed * 0x5DEECE66DL + 0xBL) & 0xFFFFFFFFFFFFL
      val nextRNG = SimpleRNG(newSeed)
      val n = (newSeed >>> 16).toInt
      (n, nextRNG)
   }
}
```

Then exercise 6.1 on page 82 (103 electronic version) says: 

> Write a function that uses RNG.nextInt to generate a random integer between 0 and
> Int.maxValue (inclusive). Make sure to handle the corner case when nextInt returns
> Int.MinValue, which doesn’t have a non-negative counterpart.

The last sentence: _Make sure to handle the corner case when nextInt returns Int.MinValue, which doesn’t have a non-negative counterpart_ has a small issue on it, is not possible to get `Int.minValue` from that algorithm, as there is no integer `seed` value that generates it.

To prove it, we'll isolate `seed` in the following expression:

```
 (newSeed >>> 16)  = (seed * 0x5DEECE66DL + 0xBL) & 0xFFFFFFFFFFFFL
```

For the purposes of the proof we can safely remove the `& 0xFFFFFFFFFFFFL` from the right side which only purpose is to keep the expression in a 64-bits long data type.

```
  (newSeed >>> 16) = seed * 0x5DEECE66DL + 0xBL
```

Replacing `newSeed` with `Int.minValue` and we have:

```
  (Int.minValue >>> 16) = seed * 0x5DEECE66DL + 0xBL
```

Solving the equation for `seed`:

```
   seed = ((Int.minValue * 2^16) - 0xBL) / 0x5DEECE66DL     // We multiply by 2^16 to remove the right shift 16

   seed = ((-2147483648 * 65535) - 11) / 25214903917

   seed = -5581.43474728081788549771
```

`seed` is not a integer value, then is not possible to obtain `Int.minValue` from the algorithm.

The program below is a brute force search that confirms that an integer value for `seed` that generates `Int.minValue` does not exists.

``` cpp
#include <iostream>
#include <cstdlib>
#include <limits>
#include <bitset>

int64_t nextInt(int64_t seed) {
   int64_t newSeed = seed * 0x5DEECE66DL + 0xBL;
   int64_t n = newSeed >> 16;
}

std::string toBinStr64(int64_t val) {
   return std::bitset<64>(val).to_string();
} 

int main() {
    const int64_t offset = 0xB;
    const int64_t factor = 0x5DEECE66DL;

    const int64_t _2_pow_16 = 65535;
    for (int64_t v1 = 0; v1 <= _2_pow_16; v1++) {
        for (int64_t v2 = 0; v2 <= _2_pow_16; v2++) {
            // MIN_INTEGER in binary
            int64_t r = 0b100000000000000000000000000000000000000000000000;
            r = (v1 << 48) | r | v2;

            // std::cout << "r = " << toBinStr64(r) << std::endl;
            int64_t seed = (r - offset) / factor;

            int64_t prandom = nextInt(seed);
            if (static_cast<int>(prandom) == std::numeric_limits<int>::min()) {
                std::cout << "Found one seed" 
                    << seed  << " = " << toBinStr64(seed) 
                    << " yields " << r << std::endl;
            }
        }
    }
    return 0;
}
```

**Comment by arobson73** [comment]
are you sure :)
try this 
    def checkRange(count:Long,mi:Int,mx:Int)(rng: RNG) = {
       def go(count:Long, r: RNG): Unit =
      {
         val (x, r2) = r.nextInt
         if ((x >= mi && x <= mx) || count == 0) println(s"x= $x, count= $count")
         else go(count-1,r2)
        }
         go(count,rng)
      }

my input to this function was
checkRange(Long.MaxValue,Int.MinValue,Int.MinValue)(Simple(19191913))

**Comment by woofyzhao** [comment]
the point is you have to assume that it does

**Comment by higuaro** [comment]
Sorry, there is a mistake in the proof, my bad. :sweat:

**Comment by vujadetech** [comment]
Regardless, it's not a big deal to deal with it: just map it to 0 to make sure the distribution is uniform.

def nonNegInt(rng: RNG): (Int, RNG) = rng.nextInt match {
  case (Int.MinValue, r2) => (0,      r2) 
  case (x, r2) if (x < 0) => (x.abs,  r2)
  case (x, r2)            => (x     , r2)
}
