### ISSUE TITLE
Chapter 9.2 (page 152) val numA 

### ISSUE THREAD

**Issue by gtrefs** [fpinscala/fpinscala#506]
Thanks for this wonderful book.  So far, it is one of the best books I read. 

I am not sure but I think I found a little failure in chapter 9.2. On page 152 in chapter `A possible algebra` you define `numA` as follows:

> `val numA: Parser[Int] = char('a').many.map(_.size)`

If I read this correctly then this should parse any string which just contains `a`. So `run(numA)("aaa") == Right(3)` should be true. However, you are also stating that `run(numA)("b") == Right(0)` which I expect to be a `Left(ParseError)` because `char('a')` cannot parse character `"b"`. Especially, when we take the expectations towards `map` into account:

> We have a strong expectation for the behavior of map — it should merely transform the result value if the Parser was successful. No additional input characters should be examined by map , and a failing parser can’t become a successful one via map or vice versa.

What do you think?

**Comment by arobson73** [comment]
i think the many function detects zero or more occurances of 'a'. At that stage of the book i think there is no concrete implementation, its just desigining an algebra.

**Comment by gtrefs** [comment]
Ah... thanks. That is it.
