### ISSUE TITLE
Exercise 3.5

### ISSUE THREAD

**Issue by fricaro** [fpinscala/fpinscala#627]
Implementation of dropWhile in the answer key for chapter 3 is:

```
def dropWhile[A](l: List[A], f: A => Boolean): List[A] =
  l match
    case Cons(h,t) if f(h) => dropWhile(t, f)
    case _ => l
```

But should be something like:

```
  def dropWhile[A](l: List[A], f: A => Boolean): List[A] = l match {
    case Nil => l
    case Cons(x, l) if (f(x)) => dropWhile(l, f)
    case Cons(x, l) => Cons(x, dropWhile(l, f))
  }
```

**Comment by luizgribeiro** [comment]
The exercise description says "Implement `dropWhile`, which removes elements from the List's prefix as long as they match a predicate". The main idea here is that whenever the predicate returns false this is the return of the method. The first solution fulfill the task. 

The second one looks like a `filter`, in which whenever the predicate return false the element is "removed" from the original list

**Comment by fricaro** [comment]
Yes! You're right, I got confused by the description of the function. "as long as they match a predicate" had me thinking I should check every element of the list instead of halting when the match occurs. Thank you, luiz!
