### ISSUE TITLE
2nd Ed. : Wrong Signature For Exercise 7.2 ?

### ISSUE THREAD

**Issue by Haidar0096** [fpinscala/fpinscala#640]
where is the `a` coming from in the definition of `run` in exercise 7.2 ?

![image](https://user-images.githubusercontent.com/49842031/155955474-8568a11c-3bc1-4cc3-b482-80f7d6e4c06d.png)

Also, the return type should be `Future[A]` and not `A`.

Am I missing something or the signature is wrong? shouldn't it be `def run(s: ExecutorService): Future[A] = pa(s)` ?

**Comment by mpilquist** [comment]
Yep, there are two typos in the published MEAP. The corrected version is below, which will be in the next MEAP update (hopefully very soon):

```scala
opaque type Par[A] = ExecutorService => Future[A]

extension [A](pa: Par[A]) def run(s: ExecutorService): Future[A] = pa(s)
```
