### ISSUE TITLE
Answer 5.2 - Functional_Programming_in_Scala_Second__v7

### ISSUE THREAD

**Issue by cruiztorresj** [fpinscala/fpinscala#669]
Result type for `take(n)` (In the proposed answer [Page 102]) function should be `A` instead of `Int` if the reader is using the `LazyList` definition provided in Listing 5.2 (Page 91).

Like `def take(n: Int): MyLazyList[A]`

Thanks for having written this amazing book.

--
Caleb.

**Comment by mpilquist** [comment]
Thanks for spotting! Fixed in the manuscript.
