### ISSUE TITLE
Unrecognized VM option when using JDK 17

### ISSUE THREAD

**Issue by evanchaney** [fpinscala/fpinscala#670]
When running `./sbt` per the README to build the code for the first time startup fails with the error “Unrecognized VM option 'CMSClassUnloadingEnabled'”.

This appears to be an incompatibility between the script and newer versions of Java.

```
ec-home:fpinscala-fpinscala evan$ ./sbt
Unrecognized VM option 'CMSClassUnloadingEnabled'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Changing JDKs to version 11 works around the issue.

Observed under environment:

- JDK: Temurin 17.0.5
- fpinscala revision: da183734af0ebbc1c0ae8fa4bd9e8ec5acbd1216 (HEAD of first-edition)
- Operating system: macOS 13.0.1

**Comment by mpilquist** [comment]
The sbt launcher script included in the first edition branch is indeed out of date. The officially recommended approach from SBT team is to remove the custom launcher and direct folks to https://www.scala-sbt.org for installation instructions. A PR that updates docs and removes `sbt` script would be very welcome.

**Comment by cruiztorresj** [comment]
Mr. Pilquist, couldn't help creating the very welcome PR you are mentioning in the answer for this issue.
https://github.com/fpinscala/fpinscala/pull/671

--
Caleb
