### ISSUE TITLE
Scala Test Failing

### ISSUE THREAD

**Issue by isarwarfp** [fpinscala/fpinscala#675]
When running the command
```scala
scala-cli test .
```
It fails on many tests from `MonoidSuite` and `JSONSuite`, even from other more.
Even `ParsersSuite` is commented.
Repository is not in stable state :(

**Comment by mpilquist** [comment]
That’s intentional - the idea is that tests will gradually start passing as you implement the exercises.

**Comment by isarwarfp** [comment]
Sounds fair, for the sake of a thought, there should be `test` for `answers` package.
